version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    volumes:
      - 'redis_vol:/data'
    ports:
      - '6379:6379'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=redis_password
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_password


  postgres:
    container_name: postgres-db
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181


volumes:
  redis_vol:
    driver: local
